apiVersion: apps/v1
kind: Deployment
metadata:
  name: jnb-ping-pong
  namespace: jnb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ping-pong
      owner: jnb
  template:
    metadata:
      labels:
        app: ping-pong
        owner: jnb
    spec:
      containers:
      - name: jnb-ping-pong
        image: ninckblokje/ping-pong:latest
        ports:
        - containerPort: 9080
---
kind: Service
apiVersion: v1
metadata:
  name: jnb-ping-pong
  labels:
    app: ping-pong
    owner: jnb
  namespace: jnb
spec:
  type: NodePort
  selector:
    app: ping-pong
    owner: jnb
  ports:
  - name: http
    port: 80
    targetPort: 9080
    nodePort: 31080